apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-user-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-user-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-user-mysql
    spec:
      containers:
        - name: ts-user-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-user-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-auth-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-auth-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-auth-mysql
    spec:
      containers:
        - name: ts-auth-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-auth-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-route-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-route-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-route-mysql
    spec:
      containers:
        - name: ts-route-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-route-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-contacts-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-contacts-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-contacts-mysql
    spec:
      containers:
        - name: ts-contacts-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-contacts-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-order-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-order-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-order-mysql
    spec:
      containers:
        - name: ts-order-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-order-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-order-other-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-order-other-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-order-other-mysql
    spec:
      containers:
        - name: ts-order-other-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-order-other-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-config-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-config-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-config-mysql
    spec:
      containers:
        - name: ts-config-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-config-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-station-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-station-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-station-mysql
    spec:
      containers:
        - name: ts-station-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-station-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-train-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-train-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-train-mysql
    spec:
      containers:
        - name: ts-train-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-train-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-travel-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-travel-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-travel-mysql
    spec:
      containers:
        - name: ts-travel-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-travel-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-travel2-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-travel2-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-travel2-mysql
    spec:
      containers:
        - name: ts-travel2-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-travel2-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-price-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-price-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-price-mysql
    spec:
      containers:
        - name: ts-price-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-price-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-security-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-security-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-security-mysql
    spec:
      containers:
        - name: ts-security-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-security-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-inside-payment-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-inside-payment-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-inside-payment-mysql
    spec:
      containers:
        - name: ts-inside-payment-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-inside-payment-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-payment-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-payment-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-payment-mysql
    spec:
      containers:
        - name: ts-payment-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-payment-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-assurance-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-assurance-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-assurance-mysql
    spec:
      containers:
        - name: ts-assurance-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-assurance-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-ticket-office-mongo
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-ticket-office-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-ticket-office-mongo
    spec:
      containers:
        - name: ts-ticket-office-mongo
          image: mongo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-voucher-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-voucher-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-voucher-mysql
    spec:
      containers:
        - name: ts-voucher-mysql
          image: mysql:5.6.35
          imagePullPolicy: IfNotPresent
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-food-map-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-food-map-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-food-map-mysql
    spec:
      containers:
        - name: ts-food-map-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-food-map-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-consign-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-consign-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-consign-mysql
    spec:
      containers:
        - name: ts-consign-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-consign-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-consign-price-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-consign-price-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-consign-price-mysql
    spec:
      containers:
        - name: ts-consign-price-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-consign-price-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-food-mysql
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-food-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-food-mysql
    spec:
      containers:
        - name: ts-food-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ts-food-mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: ts-user-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-user-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-auth-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-auth-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: ts-route-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-route-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-contacts-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-contacts-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-order-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-order-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-order-other-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-order-other-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: ts-config-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-config-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-station-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-station-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-train-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-train-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-travel-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-travel-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-travel2-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-travel2-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-price-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-price-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-security-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-security-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-inside-payment-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-inside-payment-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-payment-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-payment-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-assurance-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-assurance-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-ticket-office-mongo
  namespace: h10g
spec:
  ports:
    - port: 27017
  selector:
    app: ts-ticket-office-mongo

---
apiVersion: v1
kind: Service
metadata:
  name: ts-voucher-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-voucher-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-food-map-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-food-map-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-consign-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-consign-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-consign-price-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-consign-price-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ts-food-mysql
  namespace: h10g
spec:
  ports:
    - port: 3306
  selector:
    app: ts-food-mysql
