apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-ui-dashboard
  namespace: h10g
spec:
  selector:
    matchLabels:
      app: ts-ui-dashboard
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-ui-dashboard
    spec:
      containers:
        - name: ts-ui-dashboard
          image: registry.cn-hangzhou.aliyuncs.com/maturity/ts-ui-dashboard:sw1.0
          imagePullPolicy: Always
          env:
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "collector.trace.svc.cluster.local:3200"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi

---
apiVersion: v1
kind: Service
metadata:
  name: ts-ui-dashboard
  namespace: h10g
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 31777
  selector:
    app: ts-ui-dashboard
---

