apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: ase-ns-14
spec:
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: registry.cn-hangzhou.aliyuncs.com/xywu/eureka-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8761

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ase-ns-14
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: registry.cn-hangzhou.aliyuncs.com/xywu/api-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 9999

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ase-ns-14
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: registry.cn-hangzhou.aliyuncs.com/xywu/user-service
          imagePullPolicy: Always
          ports:
            - containerPort: 12401

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-service
  namespace: ase-ns-14
spec:
  selector:
    matchLabels:
      app: meeting-service
  template:
    metadata:
      labels:
        app: meeting-service
    spec:
      containers:
        - name: meeting-service
          image: registry.cn-hangzhou.aliyuncs.com/xywu/meeting-service
          imagePullPolicy: Always
          ports:
            - containerPort: 12301

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-service
  namespace: ase-ns-14
spec:
  selector:
    matchLabels:
      app: article-service
  template:
    metadata:
      labels:
        app: article-service
    spec:
      containers:
        - name: article-service
          image: registry.cn-hangzhou.aliyuncs.com/xywu/article-service
          imagePullPolicy: Always
          ports:
            - containerPort: 12803

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcmember-service
  namespace: ase-ns-14
spec:
  selector:
    matchLabels:
      app: pcmember-service
  template:
    metadata:
      labels:
        app: pcmember-service
    spec:
      containers:
        - name: pcmember-service
          image: registry.cn-hangzhou.aliyuncs.com/xywu/pcmember-service
          imagePullPolicy: Always
          ports:
            - containerPort: 12305

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: ase-ns-14
spec:
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: registry.cn-hangzhou.aliyuncs.com/xywu/review-service
          imagePullPolicy: Always
          ports:
            - containerPort: 12306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: ase-ns-14
spec:
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
        - name: message-service
          image: registry.cn-hangzhou.aliyuncs.com/xywu/message-service
          imagePullPolicy: Always
          ports:
            - containerPort: 12406

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyber-frontend
  namespace: ase-ns-14
spec:
  selector:
    matchLabels:
      app: cyber-frontend
  template:
    metadata:
      labels:
        app: cyber-frontend
    spec:
      containers:
        - name: cyber-frontend
          image: registry.cn-hangzhou.aliyuncs.com/xywu/cyber-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: ase-ns-14
spec:
  type: NodePort
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: ase-ns-14
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
      nodePort: 30009

---
apiVersion: v1
kind: Service
metadata:
  name: cyber-frontend
  namespace: ase-ns-14
spec:
  type: NodePort
  selector:
    app: cyber-frontend
  ports:
    - protocol: TCP
      port: 1204
      targetPort: 80
      nodePort: 30004
