apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: strange-lib
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: registry.cn-shanghai.aliyuncs.com/strangelib/strangelibrary_mysql:v2
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: strange-lib
spec:
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
        - name: service-discovery
          image: registry.cn-shanghai.aliyuncs.com/strangelib/strangelibrary_service-discovery:v2
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: USERNAME
              value: root
            - name: PASSWORD
              value: password
            - name: DB_URL
              value: mysql:3306/book
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "collector.trace.svc.cluster.local:3200"
          ports:
            - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: strange-lib
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: registry.cn-shanghai.aliyuncs.com/strangelib/strangelibrary_user-service:v3
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: USERNAME
              value: root
            - name: PASSWORD
              value: password
            - name: DB_URL
              value: mysql:3306/book
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "collector.trace.svc.cluster.local:3200"
          ports:
            - containerPort: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: strange-lib
spec:
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: registry.cn-shanghai.aliyuncs.com/strangelib/strangelibrary_book-service:v3
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: USERNAME
              value: root
            - name: PASSWORD
              value: password
            - name: DB_URL
              value: mysql:3306/book
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "collector.trace.svc.cluster.local:3200"
          ports:
            - containerPort: 9091

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
  namespace: strange-lib
spec:
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - name: mail-service
          image: registry.cn-shanghai.aliyuncs.com/strangelib/strangelibrary_mail-service:v3
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: USERNAME
              value: root
            - name: PASSWORD
              value: password
            - name: DB_URL
              value: mysql:3306/book
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "collector.trace.svc.cluster.local:3200"
          ports:
            - containerPort: 9080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrow-service
  namespace: strange-lib
spec:
  selector:
    matchLabels:
      app: borrow-service
  template:
    metadata:
      labels:
        app: borrow-service
    spec:
      containers:
        - name: borrow-service
          image: registry.cn-shanghai.aliyuncs.com/strangelib/strangelibrary_borrow-service:v3
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: USERNAME
              value: root
            - name: PASSWORD
              value: password
            - name: DB_URL
              value: mysql:3306/book
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "collector.trace.svc.cluster.local:3200"
          ports:
            - containerPort: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
  namespace: strange-lib
spec:
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - name: comment-service
          image: registry.cn-shanghai.aliyuncs.com/strangelib/strangelibrary_comment-service:v3
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: USERNAME
              value: root
            - name: PASSWORD
              value: password
            - name: DB_URL
              value: mysql:3306/book
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "collector.trace.svc.cluster.local:3200"
          ports:
            - containerPort: 9093

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-service
  namespace: strange-lib
spec:
  selector:
    matchLabels:
      app: logger-service
  template:
    metadata:
      labels:
        app: logger-service
    spec:
      containers:
        - name: logger-service
          image: registry.cn-shanghai.aliyuncs.com/strangelib/strangelibrary_logger-service:v3
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: USERNAME
              value: root
            - name: PASSWORD
              value: password
            - name: DB_URL
              value: mysql:3306/book
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "collector.trace.svc.cluster.local:3200"
          ports:
            - containerPort: 9099

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: violation-service
  namespace: strange-lib
spec:
  selector:
    matchLabels:
      app: violation-service
  template:
    metadata:
      labels:
        app: violation-service
    spec:
      containers:
        - name: violation-service
          image: registry.cn-shanghai.aliyuncs.com/strangelib/strangelibrary_violation-service:v3
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: USERNAME
              value: root
            - name: PASSWORD
              value: password
            - name: DB_URL
              value: mysql:3306/book
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "collector.trace.svc.cluster.local:3200"
          ports:
            - containerPort: 9094

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: se-frontend-server
  namespace: strange-lib
spec:
  selector:
    matchLabels:
      app: se-frontend-server
  template:
    metadata:
      labels:
        app: se-frontend-server
    spec:
      containers:
        - name: se-frontend-server
          image: registry.cn-shanghai.aliyuncs.com/strangelib/strangelibrary_se-frontend-server:v2
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: USERNAME
              value: root
            - name: PASSWORD
              value: password
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "collector.trace.svc.cluster.local:3200"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: strange-lib
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - port: 3306
      nodePort: 30006

---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: strange-lib
spec:
  selector:
    app: service-discovery
  ports:
    - protocol: TCP
      port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: strange-lib
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: strange-lib
spec:
  selector:
    app: book-service
  ports:
    - protocol: TCP
      port: 9091

---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
  namespace: strange-lib
spec:
  selector:
    app: mail-service
  ports:
    - protocol: TCP
      port: 9080

---
apiVersion: v1
kind: Service
metadata:
  name: borrow-service
  namespace: strange-lib
spec:
  selector:
    app: borrow-service
  ports:
    - protocol: TCP
      port: 9092

---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
  namespace: strange-lib
spec:
  selector:
    app: comment-service
  ports:
    - protocol: TCP
      port: 9093

---
apiVersion: v1
kind: Service
metadata:
  name: logger-service
  namespace: strange-lib
spec:
  selector:
    app: logger-service
  ports:
    - protocol: TCP
      port: 9099

---
apiVersion: v1
kind: Service
metadata:
  name: violation-service
  namespace: strange-lib
spec:
  selector:
    app: violation-service
  ports:
    - protocol: TCP
      port: 9094

---
apiVersion: v1
kind: Service
metadata:
  name: se-frontend-server
  namespace: strange-lib
spec:
  type: NodePort
  selector:
    app: se-frontend-server
  ports:
    - protocol: TCP
      port: 80
      nodePort: 32677
